apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-db
  labels:
    app: app-greeting-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-greeting-springboot
  template:
    metadata:
      labels:
        app: app-greeting-springboot
    spec:
      containers:
      - name: greeting-db-container
        image: nelvadas/modelis-postgresql:1.0.1
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        ports:
        - containerPort: 5432
        
            
           





