apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-db
  labels:
    app: app-greeting-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-greeting-springboot
  template:
    metadata:
      labels:
        app: app-greeting-springboot
    spec:
      containers:
      - name: greeting-db
        image: nelvadas/modelis-postgresql:1.0.1
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-greeting-springboot
  name: greeting-db-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 35432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: app-greeting-springboot
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
