apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-db
  labels:
    app: app-greeting-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-greeting-springboot
  template:
    metadata:
      labels:
        app: app-greeting-springboot
    spec:
      containers:
      - name: greeting-db
        image: nelvadas/modelis-postgresql:1.0.1
        ports:
        - containerPort: 5432
