apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-greeting-springboot
  name: greeting-svc2
spec:
  clusterIP: 10.108.18.168
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32100
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-greeting-springboot
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
