# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Recuperer le code source
      uses: actions/checkout@v2
    - name: Installer JDK8 et Maven
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compiler le JAR
      run: mvn -B package --file pom.xml
    
    
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le Dossier Target
        run:  ls -rtl
      - name: PWD
        run: pwd
      - name: Constuire l'image Docker 
